package com.rpgsim.server;

import com.rpgsim.common.sheets.Account;
import com.rpgsim.common.sheets.PlayerSheet;
import com.rpgsim.server.util.SheetManager;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class ServerFrame extends javax.swing.JFrame
{
    private final ServerSheetFrame sheetFrame;
    private PlayerSheet playerSheet;
    private final DefaultListModel<Account> list = new DefaultListModel<>();
    private boolean loaded = false;
    
    public ServerFrame(ServerSheetFrame sheetFrame)
    {
        initComponents();
        
        this.sheetFrame = sheetFrame;
        
        this.sheetFrame.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                playerSheet = null;
            }
        });
        
        this.lstPlayer.setModel(list);
        btnOpenCharacterSheet.addActionListener(l -> 
        {
            int i = lstPlayer.getSelectedIndex();
            if (i < 0)
            {
                JOptionPane.showMessageDialog(null, "You should select an account first!");
                return;
            }
            
            if (playerSheet != null)
            {
                JOptionPane.showMessageDialog(null, "You should close the sheet that is opened first befora opening another one.");
                return;
            }
            
            Account acc = list.get(i);
            playerSheet = acc.getPlayerSheet();
            
            if (loaded)
                sheetFrame.reload(acc.getConnectionID(), playerSheet);
            else
            {
                sheetFrame.load(acc.getConnectionID(), SheetManager.getDefaultSheetModel(), playerSheet, false);
                loaded = true;
            }
            
            sheetFrame.setVisible(true);
        });
    }
    
    public void addPlayer(Account acc)
    {
        list.addElement(acc);
        sheetFrame.addActiveSheet(acc.getConnectionID(), acc.getPlayerSheet());
    }
    
    public void removePlayer(Account acc)
    {
        if (acc.getPlayerSheet().equals(playerSheet))
            sheetFrame.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        list.removeElement(acc);
        sheetFrame.removeActiveSheet(acc.getConnectionID());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPlayer = new javax.swing.JScrollPane();
        lstPlayer = new javax.swing.JList<>();
        btnOpenCharacterSheet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("RPG Simulator Server");

        scrPlayer.setViewportView(lstPlayer);

        btnOpenCharacterSheet.setText("Open Character Sheet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(btnOpenCharacterSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpenCharacterSheet)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenCharacterSheet;
    private javax.swing.JList<Account> lstPlayer;
    private javax.swing.JScrollPane scrPlayer;
    // End of variables declaration//GEN-END:variables

}
